# Site settings
title: Light & Free Escapes
client:
  name: Light & Free
  link: http://www.lightandfree.com/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Take the leap into the unknown. We’ve partnered with Light & Free to bring you eight deliciously secret getaways. So if you’re ready to throw yourself into an escape filled with unforgettable adventure, don’t miss your chance to win the experience of a lifetime.

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/lightandfree" # the subpath of the site, including territory and year
img:     "/uk/2020/lightandfree/_assets/img"
css:     "/uk/2020/lightandfree/_assets/css"
js:      "/uk/2020/lightandfree/_assets/js"
video:   "/uk/2020/lightandfree/_assets/video"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed